CREATE SCHEMA "pos";
--> statement-breakpoint
CREATE TABLE "pos"."audit_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action" text NOT NULL,
	"actor_id" integer,
	"actor_name" text DEFAULT '' NOT NULL,
	"detail" text DEFAULT '' NOT NULL,
	"ref_type" text,
	"ref_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."audit_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"tax_id" text DEFAULT '' NOT NULL,
	"branch" text DEFAULT '' NOT NULL,
	"address" text,
	"phone" text DEFAULT '' NOT NULL,
	"vehicle_plate" text DEFAULT '' NOT NULL,
	"credit_limit" numeric(18, 3) DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."customers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."debt_payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."debt_payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"payment_no" text NOT NULL,
	"customer_id" integer NOT NULL,
	"amount" numeric(18, 3) NOT NULL,
	"method" text DEFAULT 'cash' NOT NULL,
	"shift_id" integer,
	"staff_name" text DEFAULT '' NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "debt_payments_payment_no_unique" UNIQUE("payment_no")
);
--> statement-breakpoint
ALTER TABLE "pos"."debt_payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."employee_profiles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."employee_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"staff_id" integer NOT NULL,
	"position" text DEFAULT '' NOT NULL,
	"salary_type" text DEFAULT 'monthly' NOT NULL,
	"base_rate" numeric(18, 3) DEFAULT 0 NOT NULL,
	"overtime_rate" numeric(18, 3) DEFAULT 0 NOT NULL,
	"hire_date" text,
	"note" text
);
--> statement-breakpoint
ALTER TABLE "pos"."employee_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."expenses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."expenses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"category" text DEFAULT '' NOT NULL,
	"amount" numeric(18, 3) NOT NULL,
	"shift_id" integer,
	"staff_name" text DEFAULT '' NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."expenses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."fuel_tanks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."fuel_tanks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"name" text NOT NULL,
	"capacity_liters" numeric(18, 3) NOT NULL,
	"current_liters" numeric(18, 3) DEFAULT 0 NOT NULL,
	"low_alert_at" numeric(18, 3) DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."fuel_tanks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"member_code" text NOT NULL,
	"name" text NOT NULL,
	"phone" text NOT NULL,
	"points" integer DEFAULT 0 NOT NULL,
	"tier" text DEFAULT 'silver' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "members_member_code_unique" UNIQUE("member_code"),
	CONSTRAINT "members_phone_unique" UNIQUE("phone")
);
--> statement-breakpoint
ALTER TABLE "pos"."members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."nozzles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."nozzles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pump_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"tank_id" integer,
	"label" text NOT NULL,
	"current_meter" numeric(18, 3) DEFAULT 0 NOT NULL,
	"current_money" numeric(18, 3) DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."nozzles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."payroll_records" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."payroll_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"payroll_month" text NOT NULL,
	"staff_id" integer NOT NULL,
	"work_days" integer DEFAULT 0 NOT NULL,
	"work_hours" numeric(18, 3) DEFAULT 0 NOT NULL,
	"base_amount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"overtime_hours" numeric(18, 3) DEFAULT 0 NOT NULL,
	"overtime_amount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"bonus" numeric(18, 3) DEFAULT 0 NOT NULL,
	"deduction" numeric(18, 3) DEFAULT 0 NOT NULL,
	"net_amount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"paid_at" timestamp with time zone,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."payroll_records" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."point_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."point_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"member_id" integer NOT NULL,
	"sale_id" integer,
	"type" text NOT NULL,
	"points" integer NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."point_transactions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."price_changes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."price_changes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer,
	"product_code" text DEFAULT '' NOT NULL,
	"product_name" text DEFAULT '' NOT NULL,
	"old_price" numeric(18, 3) NOT NULL,
	"new_price" numeric(18, 3) NOT NULL,
	"changed_by" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."price_changes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"unit" text DEFAULT 'ชิ้น' NOT NULL,
	"price" numeric(18, 3) NOT NULL,
	"cost" numeric(18, 3) DEFAULT 0 NOT NULL,
	"stock_qty" numeric(18, 3) DEFAULT 0 NOT NULL,
	"low_stock_at" numeric(18, 3) DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "pos"."products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."pumps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."pumps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."pumps" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."reward_redemptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."reward_redemptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"member_id" integer NOT NULL,
	"reward_id" integer NOT NULL,
	"points_used" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."reward_redemptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."rewards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."rewards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"points_required" integer NOT NULL,
	"stock" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."rewards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."sale_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."sale_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sale_id" integer NOT NULL,
	"product_id" integer,
	"name" text NOT NULL,
	"qty" numeric(18, 3) NOT NULL,
	"unit" text DEFAULT 'ชิ้น' NOT NULL,
	"unit_price" numeric(18, 3) NOT NULL,
	"amount" numeric(18, 3) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."sale_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."sales" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."sales_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"receipt_no" text NOT NULL,
	"shift_id" integer,
	"staff_name" text DEFAULT '' NOT NULL,
	"member_id" integer,
	"customer_id" integer,
	"subtotal" numeric(18, 3) NOT NULL,
	"discount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"vat_rate" numeric(18, 3) DEFAULT 7 NOT NULL,
	"vat_amount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"total" numeric(18, 3) NOT NULL,
	"payment_method" text DEFAULT 'cash' NOT NULL,
	"received" numeric(18, 3) DEFAULT 0 NOT NULL,
	"change_amt" numeric(18, 3) DEFAULT 0 NOT NULL,
	"points_earned" integer DEFAULT 0 NOT NULL,
	"points_redeemed" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'completed' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sales_receipt_no_unique" UNIQUE("receipt_no")
);
--> statement-breakpoint
ALTER TABLE "pos"."sales" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."shift_readings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."shift_readings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shift_id" integer NOT NULL,
	"nozzle_id" integer NOT NULL,
	"open_meter" numeric(18, 3) NOT NULL,
	"close_meter" numeric(18, 3),
	"open_money" numeric(18, 3) DEFAULT 0 NOT NULL,
	"close_money" numeric(18, 3),
	"price_per_liter" numeric(18, 3) DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."shift_readings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."shifts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."shifts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"staff_id" integer,
	"staff_name" text NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"closed_at" timestamp with time zone,
	"status" text DEFAULT 'open' NOT NULL,
	"total_liters" numeric(18, 3) DEFAULT 0 NOT NULL,
	"total_amount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"total_money_meter" numeric(18, 3) DEFAULT 0 NOT NULL,
	"pos_amount" numeric(18, 3) DEFAULT 0 NOT NULL,
	"counted_cash" numeric(18, 3),
	"transfer_amount" numeric(18, 3),
	"opening_float" numeric(18, 3) DEFAULT 0 NOT NULL,
	"expected_cash" numeric(18, 3),
	"cash_counts" text,
	"note" text
);
--> statement-breakpoint
ALTER TABLE "pos"."shifts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."staff_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."staff_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"pin" text NOT NULL,
	"name" text NOT NULL,
	"role" text DEFAULT 'cashier' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "staff_users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "pos"."staff_users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."tank_refills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."tank_refills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tank_id" integer NOT NULL,
	"liters" numeric(18, 3) NOT NULL,
	"cost_per_liter" numeric(18, 3) DEFAULT 0 NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."tank_refills" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."tax_invoices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."tax_invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tax_invoice_no" text NOT NULL,
	"sale_id" integer NOT NULL,
	"customer_name" text NOT NULL,
	"customer_tax_id" text DEFAULT '' NOT NULL,
	"customer_branch" text DEFAULT '' NOT NULL,
	"customer_address" text,
	"customer_phone" text DEFAULT '' NOT NULL,
	"vehicle_plate" text DEFAULT '' NOT NULL,
	"issued_by" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tax_invoices_tax_invoice_no_unique" UNIQUE("tax_invoice_no"),
	CONSTRAINT "tax_invoices_sale_id_unique" UNIQUE("sale_id")
);
--> statement-breakpoint
ALTER TABLE "pos"."tax_invoices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."work_schedules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."work_schedules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"work_date" text NOT NULL,
	"shift_template_id" integer NOT NULL,
	"staff_id" integer NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."work_schedules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."work_shift_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."work_shift_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"start_time" text NOT NULL,
	"end_time" text NOT NULL,
	"break_minutes" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."work_shift_templates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."audit_logs" ADD CONSTRAINT "audit_logs_actor_id_staff_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."debt_payments" ADD CONSTRAINT "debt_payments_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "pos"."customers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."debt_payments" ADD CONSTRAINT "debt_payments_shift_id_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "pos"."shifts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."employee_profiles" ADD CONSTRAINT "employee_profiles_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."expenses" ADD CONSTRAINT "expenses_shift_id_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "pos"."shifts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."fuel_tanks" ADD CONSTRAINT "fuel_tanks_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "pos"."products"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."nozzles" ADD CONSTRAINT "nozzles_pump_id_pumps_id_fk" FOREIGN KEY ("pump_id") REFERENCES "pos"."pumps"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."nozzles" ADD CONSTRAINT "nozzles_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "pos"."products"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."nozzles" ADD CONSTRAINT "nozzles_tank_id_fuel_tanks_id_fk" FOREIGN KEY ("tank_id") REFERENCES "pos"."fuel_tanks"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."payroll_records" ADD CONSTRAINT "payroll_records_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."point_transactions" ADD CONSTRAINT "point_transactions_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "pos"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."point_transactions" ADD CONSTRAINT "point_transactions_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "pos"."sales"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."price_changes" ADD CONSTRAINT "price_changes_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "pos"."products"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."reward_redemptions" ADD CONSTRAINT "reward_redemptions_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "pos"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."reward_redemptions" ADD CONSTRAINT "reward_redemptions_reward_id_rewards_id_fk" FOREIGN KEY ("reward_id") REFERENCES "pos"."rewards"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sale_items" ADD CONSTRAINT "sale_items_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "pos"."sales"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sale_items" ADD CONSTRAINT "sale_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "pos"."products"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sales" ADD CONSTRAINT "sales_shift_id_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "pos"."shifts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sales" ADD CONSTRAINT "sales_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "pos"."members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sales" ADD CONSTRAINT "sales_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "pos"."customers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."shift_readings" ADD CONSTRAINT "shift_readings_shift_id_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "pos"."shifts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."shift_readings" ADD CONSTRAINT "shift_readings_nozzle_id_nozzles_id_fk" FOREIGN KEY ("nozzle_id") REFERENCES "pos"."nozzles"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."shifts" ADD CONSTRAINT "shifts_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."tank_refills" ADD CONSTRAINT "tank_refills_tank_id_fuel_tanks_id_fk" FOREIGN KEY ("tank_id") REFERENCES "pos"."fuel_tanks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."tax_invoices" ADD CONSTRAINT "tax_invoices_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "pos"."sales"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."work_schedules" ADD CONSTRAINT "work_schedules_shift_template_id_work_shift_templates_id_fk" FOREIGN KEY ("shift_template_id") REFERENCES "pos"."work_shift_templates"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."work_schedules" ADD CONSTRAINT "work_schedules_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_action_idx" ON "pos"."audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_actor_idx" ON "pos"."audit_logs" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "audit_created_idx" ON "pos"."audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "debtpay_customer_idx" ON "pos"."debt_payments" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "debtpay_shift_idx" ON "pos"."debt_payments" USING btree ("shift_id");--> statement-breakpoint
CREATE INDEX "debtpay_created_idx" ON "pos"."debt_payments" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "employeeprofile_staff_unique" ON "pos"."employee_profiles" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "expenses_created_idx" ON "pos"."expenses" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "expenses_shift_idx" ON "pos"."expenses" USING btree ("shift_id");--> statement-breakpoint
CREATE INDEX "fueltank_product_idx" ON "pos"."fuel_tanks" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "pump_idx" ON "pos"."nozzles" USING btree ("pump_id");--> statement-breakpoint
CREATE INDEX "nozzle_product_idx" ON "pos"."nozzles" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "nozzle_tank_idx" ON "pos"."nozzles" USING btree ("tank_id");--> statement-breakpoint
CREATE INDEX "payroll_month_idx" ON "pos"."payroll_records" USING btree ("payroll_month");--> statement-breakpoint
CREATE UNIQUE INDEX "payroll_staff_month_unique" ON "pos"."payroll_records" USING btree ("staff_id","payroll_month");--> statement-breakpoint
CREATE INDEX "member_idx" ON "pos"."point_transactions" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "pointtransaction_sale_idx" ON "pos"."point_transactions" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "pricechg_product_idx" ON "pos"."price_changes" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "cat_idx" ON "pos"."products" USING btree ("category");--> statement-breakpoint
CREATE INDEX "rewardredemption_member_idx" ON "pos"."reward_redemptions" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "rewardredemption_reward_idx" ON "pos"."reward_redemptions" USING btree ("reward_id");--> statement-breakpoint
CREATE INDEX "sale_idx" ON "pos"."sale_items" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "saleitem_product_idx" ON "pos"."sale_items" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "created_idx" ON "pos"."sales" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "sales_shift_idx" ON "pos"."sales" USING btree ("shift_id");--> statement-breakpoint
CREATE INDEX "sales_member_idx" ON "pos"."sales" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "sales_customer_idx" ON "pos"."sales" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "sales_status_idx" ON "pos"."sales" USING btree ("status");--> statement-breakpoint
CREATE INDEX "shift_idx" ON "pos"."shift_readings" USING btree ("shift_id");--> statement-breakpoint
CREATE INDEX "shiftreading_nozzle_idx" ON "pos"."shift_readings" USING btree ("nozzle_id");--> statement-breakpoint
CREATE INDEX "shift_staff_idx" ON "pos"."shifts" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "shift_status_idx" ON "pos"."shifts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "tankrefill_tank_idx" ON "pos"."tank_refills" USING btree ("tank_id");--> statement-breakpoint
CREATE INDEX "workschedule_date_idx" ON "pos"."work_schedules" USING btree ("work_date");--> statement-breakpoint
CREATE INDEX "workschedule_staff_idx" ON "pos"."work_schedules" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "workschedule_template_idx" ON "pos"."work_schedules" USING btree ("shift_template_id");--> statement-breakpoint
CREATE UNIQUE INDEX "workschedule_assignment_unique" ON "pos"."work_schedules" USING btree ("work_date","shift_template_id","staff_id");
--> statement-breakpoint
REVOKE ALL ON SCHEMA "pos" FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
REVOKE ALL ON ALL TABLES IN SCHEMA "pos" FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
REVOKE ALL ON ALL SEQUENCES IN SCHEMA "pos" FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA "pos" REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA "pos" REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
DO $$
BEGIN
	IF to_regprocedure('public.rls_auto_enable()') IS NOT NULL THEN
		EXECUTE 'REVOKE ALL ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated';
	END IF;
END
$$;
