CREATE TABLE "pos"."staff_access_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."staff_access_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"role" text NOT NULL,
	"menu_permissions" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "staff_access_groups_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "pos"."staff_access_groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."staff_users" ADD COLUMN "access_group_id" integer;--> statement-breakpoint
ALTER TABLE "pos"."staff_users" ADD CONSTRAINT "staff_users_access_group_id_staff_access_groups_id_fk" FOREIGN KEY ("access_group_id") REFERENCES "pos"."staff_access_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
INSERT INTO "pos"."staff_access_groups" ("name", "description", "role", "menu_permissions")
VALUES
	('พนักงาน', 'กลุ่มเริ่มต้นสำหรับพนักงานหน้าลาน', 'cashier', '["dashboard","pos","shifts","workforce","stock","members","customers","debts","sales","reports","expenses","tax_invoices","settings"]'::jsonb),
	('ผู้จัดการ', 'กลุ่มเริ่มต้นสำหรับผู้จัดการสาขา', 'manager', '["dashboard","pos","shifts","workforce","stock","members","customers","debts","sales","reports","expenses","tax_invoices","documents","settings"]'::jsonb)
ON CONFLICT ("name") DO NOTHING;
