CREATE TABLE "pos"."branches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."branches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"address" text DEFAULT '' NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"tax_id" text DEFAULT '' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "branches_code_unique" UNIQUE("code")
);
--> statement-breakpoint
ALTER TABLE "pos"."branches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
INSERT INTO "pos"."branches" ("code", "name", "address", "phone", "tax_id")
SELECT
	'MAIN',
	COALESCE(MAX("value") FILTER (WHERE "key" = 'shop_branch'), 'สาขาหลัก'),
	COALESCE(MAX("value") FILTER (WHERE "key" = 'shop_address'), ''),
	COALESCE(MAX("value") FILTER (WHERE "key" = 'shop_phone'), ''),
	COALESCE(MAX("value") FILTER (WHERE "key" = 'tax_id'), '')
FROM "pos"."settings"
ON CONFLICT ("code") DO NOTHING;--> statement-breakpoint
CREATE FUNCTION "pos"."default_branch_id"()
RETURNS integer
LANGUAGE sql
STABLE
SET search_path = ''
AS $function$
	SELECT "id"
	FROM "pos"."branches"
	WHERE "code" = 'MAIN'
	ORDER BY "id"
	LIMIT 1
$function$;--> statement-breakpoint
REVOKE ALL ON FUNCTION "pos"."default_branch_id"() FROM PUBLIC, anon, authenticated;--> statement-breakpoint
CREATE TABLE "pos"."staff_branches" (
	"staff_id" integer NOT NULL,
	"branch_id" integer NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "staff_branches_pk" PRIMARY KEY("staff_id","branch_id")
);
--> statement-breakpoint
ALTER TABLE "pos"."staff_branches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."debt_payments" DROP CONSTRAINT "debt_payments_payment_no_unique";--> statement-breakpoint
ALTER TABLE "pos"."products" DROP CONSTRAINT "products_code_unique";--> statement-breakpoint
ALTER TABLE "pos"."sales" DROP CONSTRAINT "sales_receipt_no_unique";--> statement-breakpoint
ALTER TABLE "pos"."tax_invoices" DROP CONSTRAINT "tax_invoices_tax_invoice_no_unique";--> statement-breakpoint
DROP INDEX "pos"."payroll_staff_month_unique";--> statement-breakpoint
DROP INDEX "pos"."workschedule_assignment_unique";--> statement-breakpoint
ALTER TABLE "pos"."settings" DROP CONSTRAINT "settings_pkey";--> statement-breakpoint
ALTER TABLE "pos"."audit_logs" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."debt_payments" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."expenses" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."fuel_tanks" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."nozzles" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."payroll_records" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."point_transactions" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."price_changes" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."products" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."pumps" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."reward_redemptions" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."rewards" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."sale_items" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."sales" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."settings" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."settings" ADD CONSTRAINT "settings_branch_key_pk" PRIMARY KEY("branch_id","key");--> statement-breakpoint
ALTER TABLE "pos"."shift_readings" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."shifts" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."tank_refills" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."tax_invoices" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."work_schedules" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."work_shift_templates" ADD COLUMN "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL;--> statement-breakpoint
ALTER TABLE "pos"."staff_branches" ADD CONSTRAINT "staff_branches_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."staff_branches" ADD CONSTRAINT "staff_branches_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
INSERT INTO "pos"."staff_branches" ("staff_id", "branch_id", "is_default")
SELECT staff."id", branch."id", true
FROM "pos"."staff_users" AS staff
CROSS JOIN "pos"."branches" AS branch
WHERE branch."code" = 'MAIN'
ON CONFLICT ("staff_id", "branch_id") DO UPDATE SET "is_default" = true;--> statement-breakpoint
CREATE INDEX "branch_active_idx" ON "pos"."branches" USING btree ("active");--> statement-breakpoint
CREATE INDEX "staffbranch_staff_idx" ON "pos"."staff_branches" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "staffbranch_branch_idx" ON "pos"."staff_branches" USING btree ("branch_id");--> statement-breakpoint
ALTER TABLE "pos"."audit_logs" ADD CONSTRAINT "audit_logs_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."debt_payments" ADD CONSTRAINT "debt_payments_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."expenses" ADD CONSTRAINT "expenses_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."fuel_tanks" ADD CONSTRAINT "fuel_tanks_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."nozzles" ADD CONSTRAINT "nozzles_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."payroll_records" ADD CONSTRAINT "payroll_records_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."point_transactions" ADD CONSTRAINT "point_transactions_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."price_changes" ADD CONSTRAINT "price_changes_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."products" ADD CONSTRAINT "products_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."pumps" ADD CONSTRAINT "pumps_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."reward_redemptions" ADD CONSTRAINT "reward_redemptions_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."rewards" ADD CONSTRAINT "rewards_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sale_items" ADD CONSTRAINT "sale_items_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."sales" ADD CONSTRAINT "sales_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."settings" ADD CONSTRAINT "settings_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."shift_readings" ADD CONSTRAINT "shift_readings_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."shifts" ADD CONSTRAINT "shifts_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."tank_refills" ADD CONSTRAINT "tank_refills_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."tax_invoices" ADD CONSTRAINT "tax_invoices_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."work_schedules" ADD CONSTRAINT "work_schedules_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."work_shift_templates" ADD CONSTRAINT "work_shift_templates_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_branch_idx" ON "pos"."audit_logs" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "debtpay_branch_idx" ON "pos"."debt_payments" USING btree ("branch_id");--> statement-breakpoint
CREATE UNIQUE INDEX "debtpay_branch_number_unique" ON "pos"."debt_payments" USING btree ("branch_id","payment_no");--> statement-breakpoint
CREATE INDEX "expenses_branch_idx" ON "pos"."expenses" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "fueltank_branch_idx" ON "pos"."fuel_tanks" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "nozzle_branch_idx" ON "pos"."nozzles" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "payroll_branch_idx" ON "pos"."payroll_records" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "pointtransaction_branch_idx" ON "pos"."point_transactions" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "pricechg_branch_idx" ON "pos"."price_changes" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "product_branch_idx" ON "pos"."products" USING btree ("branch_id");--> statement-breakpoint
CREATE UNIQUE INDEX "product_branch_code_unique" ON "pos"."products" USING btree ("branch_id","code");--> statement-breakpoint
CREATE INDEX "pump_branch_idx" ON "pos"."pumps" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "rewardredemption_branch_idx" ON "pos"."reward_redemptions" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "reward_branch_idx" ON "pos"."rewards" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "saleitem_branch_idx" ON "pos"."sale_items" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "sales_branch_idx" ON "pos"."sales" USING btree ("branch_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sales_branch_receipt_unique" ON "pos"."sales" USING btree ("branch_id","receipt_no");--> statement-breakpoint
CREATE INDEX "settings_branch_idx" ON "pos"."settings" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "shiftreading_branch_idx" ON "pos"."shift_readings" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "shift_branch_idx" ON "pos"."shifts" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "tankrefill_branch_idx" ON "pos"."tank_refills" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "taxinvoice_branch_idx" ON "pos"."tax_invoices" USING btree ("branch_id");--> statement-breakpoint
CREATE UNIQUE INDEX "taxinvoice_branch_number_unique" ON "pos"."tax_invoices" USING btree ("branch_id","tax_invoice_no");--> statement-breakpoint
CREATE INDEX "workschedule_branch_idx" ON "pos"."work_schedules" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "workshifttemplate_branch_idx" ON "pos"."work_shift_templates" USING btree ("branch_id");--> statement-breakpoint
CREATE UNIQUE INDEX "payroll_staff_month_unique" ON "pos"."payroll_records" USING btree ("branch_id","staff_id","payroll_month");--> statement-breakpoint
CREATE UNIQUE INDEX "workschedule_assignment_unique" ON "pos"."work_schedules" USING btree ("branch_id","work_date","shift_template_id","staff_id");
