CREATE TABLE "pos"."tank_readings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."tank_readings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"tank_id" integer NOT NULL,
	"liters" numeric(18, 3) NOT NULL,
	"measured_at" timestamp with time zone DEFAULT now() NOT NULL,
	"staff_id" integer,
	"staff_name" text DEFAULT '' NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."tank_readings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."tank_readings" ADD CONSTRAINT "tank_readings_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."tank_readings" ADD CONSTRAINT "tank_readings_tank_id_fuel_tanks_id_fk" FOREIGN KEY ("tank_id") REFERENCES "pos"."fuel_tanks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."tank_readings" ADD CONSTRAINT "tank_readings_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tankreading_branch_idx" ON "pos"."tank_readings" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "tankreading_tank_idx" ON "pos"."tank_readings" USING btree ("tank_id");--> statement-breakpoint
CREATE INDEX "tankreading_measured_at_idx" ON "pos"."tank_readings" USING btree ("measured_at");