CREATE TABLE "pos"."payment_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."payment_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"ref_code" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"amount" numeric(18, 3) NOT NULL,
	"sale_id" integer,
	"confirmed_by" text,
	"external_ref" text,
	"sale_snapshot" jsonb NOT NULL,
	"last_checked_at" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."payment_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."payment_settings" (
	"branch_id" integer PRIMARY KEY NOT NULL,
	"thungngern_enabled" boolean DEFAULT false NOT NULL,
	"promptpay_id" text DEFAULT '' NOT NULL,
	"easy_api_key_encrypted" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."payment_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."payment_sessions" ADD CONSTRAINT "payment_sessions_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."payment_sessions" ADD CONSTRAINT "payment_sessions_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "pos"."sales"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."payment_settings" ADD CONSTRAINT "payment_settings_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "paymentsession_branch_idx" ON "pos"."payment_sessions" USING btree ("branch_id");--> statement-breakpoint
CREATE UNIQUE INDEX "paymentsession_branch_ref_unique" ON "pos"."payment_sessions" USING btree ("branch_id","ref_code");--> statement-breakpoint
CREATE UNIQUE INDEX "paymentsession_sale_unique" ON "pos"."payment_sessions" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "paymentsession_status_expires_idx" ON "pos"."payment_sessions" USING btree ("status","expires_at");