CREATE TABLE "pos"."stock_count_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."stock_count_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"session_id" integer NOT NULL,
	"product_id" integer,
	"product_code" text NOT NULL,
	"product_name" text NOT NULL,
	"category" text NOT NULL,
	"unit" text DEFAULT 'ชิ้น' NOT NULL,
	"expected_qty" numeric(18, 3) NOT NULL,
	"counted_qty" numeric(18, 3),
	"counted_by_id" integer,
	"counted_by_name" text,
	"counted_at" timestamp with time zone,
	"note" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."stock_count_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."stock_count_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."stock_count_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"name" text NOT NULL,
	"scope" text DEFAULT 'all' NOT NULL,
	"status" text DEFAULT 'counting' NOT NULL,
	"started_by_id" integer,
	"started_by_name" text DEFAULT '' NOT NULL,
	"completed_by_id" integer,
	"completed_by_name" text,
	"note" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."stock_count_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_items" ADD CONSTRAINT "stock_count_items_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_items" ADD CONSTRAINT "stock_count_items_session_id_stock_count_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "pos"."stock_count_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_items" ADD CONSTRAINT "stock_count_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "pos"."products"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_items" ADD CONSTRAINT "stock_count_items_counted_by_id_staff_users_id_fk" FOREIGN KEY ("counted_by_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_sessions" ADD CONSTRAINT "stock_count_sessions_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_sessions" ADD CONSTRAINT "stock_count_sessions_started_by_id_staff_users_id_fk" FOREIGN KEY ("started_by_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."stock_count_sessions" ADD CONSTRAINT "stock_count_sessions_completed_by_id_staff_users_id_fk" FOREIGN KEY ("completed_by_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "stockcountitem_branch_idx" ON "pos"."stock_count_items" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "stockcountitem_session_idx" ON "pos"."stock_count_items" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "stockcountitem_product_idx" ON "pos"."stock_count_items" USING btree ("product_id");--> statement-breakpoint
CREATE UNIQUE INDEX "stockcountitem_session_product_unique" ON "pos"."stock_count_items" USING btree ("session_id","product_id");--> statement-breakpoint
CREATE INDEX "stockcountsession_branch_idx" ON "pos"."stock_count_sessions" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "stockcountsession_status_idx" ON "pos"."stock_count_sessions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "stockcountsession_started_idx" ON "pos"."stock_count_sessions" USING btree ("started_at");--> statement-breakpoint
CREATE UNIQUE INDEX "stockcountsession_open_branch_unique" ON "pos"."stock_count_sessions" USING btree ("branch_id") WHERE "pos"."stock_count_sessions"."status" = 'counting';