CREATE TABLE IF NOT EXISTS "pos"."login_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."login_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"username" text DEFAULT '' NOT NULL,
	"success" boolean DEFAULT false NOT NULL,
	"ip" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."login_attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pos"."security_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"category" text NOT NULL,
	"severity" text NOT NULL,
	"rule" text NOT NULL,
	"title" text DEFAULT '' NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"actor_id" integer,
	"actor_name" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'new' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."security_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pos"."security_reports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."security_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"window_days" integer DEFAULT 7 NOT NULL,
	"event_count" integer DEFAULT 0 NOT NULL,
	"answer" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pos"."security_reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "pos"."login_attempts" ADD CONSTRAINT "login_attempts_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "pos"."security_events" ADD CONSTRAINT "security_events_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "pos"."security_events" ADD CONSTRAINT "security_events_actor_id_staff_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "pos"."security_reports" ADD CONSTRAINT "security_reports_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "login_attempt_username_created_idx" ON "pos"."login_attempts" USING btree ("username","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "login_attempt_ip_created_idx" ON "pos"."login_attempts" USING btree ("ip","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "security_event_branch_idx" ON "pos"."security_events" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "security_event_severity_idx" ON "pos"."security_events" USING btree ("severity");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "security_event_status_idx" ON "pos"."security_events" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "security_event_created_idx" ON "pos"."security_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "security_report_branch_idx" ON "pos"."security_reports" USING btree ("branch_id");--> statement-breakpoint
REVOKE ALL ON TABLE "pos"."login_attempts", "pos"."security_events", "pos"."security_reports" FROM public, anon, authenticated;--> statement-breakpoint
DO $$ BEGIN
	CREATE POLICY "server_only_deny_client_access" ON "pos"."login_attempts" AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	CREATE POLICY "server_only_deny_client_access" ON "pos"."security_events" AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	CREATE POLICY "server_only_deny_client_access" ON "pos"."security_reports" AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
