CREATE TABLE "pos"."member_card_batches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."member_card_batches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"batch_code" text NOT NULL,
	"label" text DEFAULT '' NOT NULL,
	"quantity" integer NOT NULL,
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"created_by_staff_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_card_batches_batch_code_unique" UNIQUE("batch_code"),
	CONSTRAINT "member_card_batches_quantity_check" CHECK ("pos"."member_card_batches"."quantity" between 1 and 500)
);
--> statement-breakpoint
ALTER TABLE "pos"."member_card_batches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pos"."member_cards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."member_cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"batch_id" integer,
	"member_code" text NOT NULL,
	"status" text DEFAULT 'unused' NOT NULL,
	"activated_member_id" integer,
	"activated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_cards_member_code_unique" UNIQUE("member_code"),
	CONSTRAINT "member_cards_activated_member_id_unique" UNIQUE("activated_member_id"),
	CONSTRAINT "member_cards_status_check" CHECK ("pos"."member_cards"."status" in ('unused', 'activated', 'void')),
	CONSTRAINT "member_cards_activation_check" CHECK (("pos"."member_cards"."status" = 'unused' and "pos"."member_cards"."activated_member_id" is null and "pos"."member_cards"."activated_at" is null)
          or ("pos"."member_cards"."status" = 'activated' and "pos"."member_cards"."activated_at" is not null)
          or ("pos"."member_cards"."status" = 'void' and "pos"."member_cards"."activated_member_id" is null))
);
--> statement-breakpoint
ALTER TABLE "pos"."member_cards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."member_card_batches" ADD CONSTRAINT "member_card_batches_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."member_card_batches" ADD CONSTRAINT "member_card_batches_created_by_staff_id_staff_users_id_fk" FOREIGN KEY ("created_by_staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."member_cards" ADD CONSTRAINT "member_cards_batch_id_member_card_batches_id_fk" FOREIGN KEY ("batch_id") REFERENCES "pos"."member_card_batches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."member_cards" ADD CONSTRAINT "member_cards_activated_member_id_members_id_fk" FOREIGN KEY ("activated_member_id") REFERENCES "pos"."members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "member_card_batches_created_idx" ON "pos"."member_card_batches" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "member_card_batches_branch_idx" ON "pos"."member_card_batches" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX "member_cards_batch_idx" ON "pos"."member_cards" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "member_cards_status_idx" ON "pos"."member_cards" USING btree ("status");--> statement-breakpoint

-- ลงทะเบียนเลขบัตร 16 หลักที่เปิดใช้งานอยู่ก่อนเพิ่มระบบสต๊อกบัตร
INSERT INTO "pos"."member_cards" (
  "member_code",
  "status",
  "activated_member_id",
  "activated_at",
  "created_at"
)
SELECT
  "member_code",
  'activated',
  "id",
  "card_activated_at",
  "created_at"
FROM "pos"."members"
WHERE "member_code" ~ '^88[0-9]{14}$'
ON CONFLICT ("member_code") DO NOTHING;--> statement-breakpoint

-- ตารางนี้ให้ Edge API ที่เชื่อม PostgreSQL โดยตรงใช้งานเท่านั้น
REVOKE ALL ON TABLE
  "pos"."member_card_batches",
  "pos"."member_cards"
FROM PUBLIC, anon, authenticated;--> statement-breakpoint

CREATE POLICY server_only_deny_client_access
  ON "pos"."member_card_batches"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);--> statement-breakpoint

CREATE POLICY server_only_deny_client_access
  ON "pos"."member_cards"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);
