CREATE TABLE "pos"."employee_face_profiles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pos"."employee_face_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
	"staff_id" integer NOT NULL,
	"template_encrypted" text NOT NULL,
	"model" text DEFAULT 'human-faceres-v1' NOT NULL,
	"embedding_count" integer NOT NULL,
	"embedding_dimensions" integer NOT NULL,
	"consent_at" timestamp with time zone NOT NULL,
	"enrolled_by_staff_id" integer NOT NULL,
	"enrolled_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "employee_face_profile_dimensions_check" CHECK ("pos"."employee_face_profiles"."embedding_count" between 3 and 5 and "pos"."employee_face_profiles"."embedding_dimensions" between 128 and 4096)
);
--> statement-breakpoint
ALTER TABLE "pos"."employee_face_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pos"."employee_face_profiles" ADD CONSTRAINT "employee_face_profiles_branch_id_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."employee_face_profiles" ADD CONSTRAINT "employee_face_profiles_staff_id_staff_users_id_fk" FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pos"."employee_face_profiles" ADD CONSTRAINT "employee_face_profiles_enrolled_by_staff_id_staff_users_id_fk" FOREIGN KEY ("enrolled_by_staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "employee_face_profile_staff_unique" ON "pos"."employee_face_profiles" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "employee_face_profile_branch_idx" ON "pos"."employee_face_profiles" USING btree ("branch_id");--> statement-breakpoint
REVOKE ALL ON TABLE "pos"."employee_face_profiles" FROM public, anon, authenticated;--> statement-breakpoint
REVOKE ALL ON SEQUENCE "pos"."employee_face_profiles_id_seq" FROM public, anon, authenticated;--> statement-breakpoint
CREATE POLICY "server_only_deny_client_access" ON "pos"."employee_face_profiles"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);
