create table "pos"."staff_access_groups" (
  "id" integer primary key generated by default as identity,
  "name" text not null unique,
  "description" text default '' not null,
  "role" text not null,
  "menu_permissions" jsonb not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

alter table "pos"."staff_access_groups" enable row level security;

alter table "pos"."staff_users"
  add column "access_group_id" integer;

alter table "pos"."staff_users"
  add constraint "staff_users_access_group_id_staff_access_groups_id_fk"
  foreign key ("access_group_id")
  references "pos"."staff_access_groups"("id")
  on delete set null;

insert into "pos"."staff_access_groups" ("name", "description", "role", "menu_permissions")
values
  ('เธเธเธฑเธเธเธฒเธ', 'เธเธฅเธธเนเธกเน€เธฃเธดเนเธกเธ•เนเธเธชเธณเธซเธฃเธฑเธเธเธเธฑเธเธเธฒเธเธซเธเนเธฒเธฅเธฒเธ', 'cashier', '["dashboard","pos","shifts","workforce","stock","members","customers","debts","sales","reports","expenses","tax_invoices","settings"]'::jsonb),
  ('เธเธนเนเธเธฑเธ”เธเธฒเธฃ', 'เธเธฅเธธเนเธกเน€เธฃเธดเนเธกเธ•เนเธเธชเธณเธซเธฃเธฑเธเธเธนเนเธเธฑเธ”เธเธฒเธฃเธชเธฒเธเธฒ', 'manager', '["dashboard","pos","shifts","workforce","stock","members","customers","debts","sales","reports","expenses","tax_invoices","documents","settings"]'::jsonb)
on conflict ("name") do nothing;;
