CREATE TABLE "pos"."member_card_batches" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "batch_code" text NOT NULL UNIQUE,
  "label" text DEFAULT '' NOT NULL,
  "quantity" integer NOT NULL,
  "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL
    REFERENCES "pos"."branches"("id") ON DELETE restrict,
  "created_by_staff_id" integer
    REFERENCES "pos"."staff_users"("id") ON DELETE set null,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "member_card_batches_quantity_check"
    CHECK ("quantity" between 1 and 500)
);

ALTER TABLE "pos"."member_card_batches" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "pos"."member_cards" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "batch_id" integer
    REFERENCES "pos"."member_card_batches"("id") ON DELETE restrict,
  "member_code" text NOT NULL UNIQUE,
  "status" text DEFAULT 'unused' NOT NULL,
  "activated_member_id" integer UNIQUE
    REFERENCES "pos"."members"("id") ON DELETE set null,
  "activated_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "member_cards_status_check"
    CHECK ("status" in ('unused', 'activated', 'void')),
  CONSTRAINT "member_cards_activation_check" CHECK (
    ("status" = 'unused' AND "activated_member_id" IS NULL AND "activated_at" IS NULL)
    OR ("status" = 'activated' AND "activated_at" IS NOT NULL)
    OR ("status" = 'void' AND "activated_member_id" IS NULL)
  )
);

ALTER TABLE "pos"."member_cards" ENABLE ROW LEVEL SECURITY;

CREATE INDEX "member_card_batches_created_idx"
  ON "pos"."member_card_batches" ("created_at");
CREATE INDEX "member_card_batches_branch_idx"
  ON "pos"."member_card_batches" ("branch_id");
CREATE INDEX "member_cards_batch_idx"
  ON "pos"."member_cards" ("batch_id");
CREATE INDEX "member_cards_status_idx"
  ON "pos"."member_cards" ("status");

INSERT INTO "pos"."member_cards" (
  "member_code",
  "status",
  "activated_member_id",
  "activated_at",
  "created_at"
)
SELECT
  "member_code",
  'activated',
  "id",
  "card_activated_at",
  "created_at"
FROM "pos"."members"
WHERE "member_code" ~ '^88[0-9]{14}$'
ON CONFLICT ("member_code") DO NOTHING;

REVOKE ALL ON TABLE
  "pos"."member_card_batches",
  "pos"."member_cards"
FROM PUBLIC, anon, authenticated;

CREATE POLICY server_only_deny_client_access
  ON "pos"."member_card_batches"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);

CREATE POLICY server_only_deny_client_access
  ON "pos"."member_cards"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);
