SET lock_timeout = '5s';
SET statement_timeout = '2min';

CREATE TABLE "pos"."employee_face_profiles" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
  "staff_id" integer NOT NULL,
  "template_encrypted" text NOT NULL,
  "model" text DEFAULT 'human-faceres-v1' NOT NULL,
  "embedding_count" integer NOT NULL,
  "embedding_dimensions" integer NOT NULL,
  "consent_at" timestamp with time zone NOT NULL,
  "enrolled_by_staff_id" integer NOT NULL,
  "enrolled_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "employee_face_profile_dimensions_check"
    CHECK ("embedding_count" BETWEEN 3 AND 5 AND "embedding_dimensions" BETWEEN 128 AND 4096)
);

ALTER TABLE "pos"."employee_face_profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "pos"."employee_face_profiles"
  ADD CONSTRAINT "employee_face_profiles_branch_id_branches_id_fk"
    FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict,
  ADD CONSTRAINT "employee_face_profiles_staff_id_staff_users_id_fk"
    FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE cascade,
  ADD CONSTRAINT "employee_face_profiles_enrolled_by_staff_id_staff_users_id_fk"
    FOREIGN KEY ("enrolled_by_staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE restrict;

CREATE UNIQUE INDEX "employee_face_profile_staff_unique"
  ON "pos"."employee_face_profiles" ("staff_id");
CREATE INDEX "employee_face_profile_branch_idx"
  ON "pos"."employee_face_profiles" ("branch_id");

-- Face templates are server-only biometric data. Browser roles may only use
-- the authenticated application API, which never returns the template.
REVOKE ALL ON TABLE "pos"."employee_face_profiles"
  FROM public, anon, authenticated;
REVOKE ALL ON SEQUENCE "pos"."employee_face_profiles_id_seq"
  FROM public, anon, authenticated;

CREATE POLICY "server_only_deny_client_access"
  ON "pos"."employee_face_profiles"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);
