SET lock_timeout = '5s';
SET statement_timeout = '2min';

CREATE TABLE "pos"."attendance_events" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
  "staff_id" integer NOT NULL,
  "session_id" integer NOT NULL,
  "event_type" text NOT NULL,
  "method" text NOT NULL,
  "occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
  "idempotency_key" text NOT NULL,
  "device_label" text,
  "metadata" jsonb,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "attendance_events_idempotency_key_unique" UNIQUE("idempotency_key")
);

ALTER TABLE "pos"."attendance_events" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "pos"."attendance_sessions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "branch_id" integer DEFAULT pos.default_branch_id() NOT NULL,
  "staff_id" integer NOT NULL,
  "schedule_id" integer,
  "work_date" text NOT NULL,
  "planned_start_at" timestamp with time zone,
  "planned_end_at" timestamp with time zone,
  "planned_break_minutes" integer DEFAULT 0 NOT NULL,
  "clock_in_at" timestamp with time zone DEFAULT now() NOT NULL,
  "clock_out_at" timestamp with time zone,
  "clock_in_method" text NOT NULL,
  "clock_out_method" text,
  "status" text DEFAULT 'open' NOT NULL,
  "review_status" text DEFAULT 'not_required' NOT NULL,
  "late_minutes" integer DEFAULT 0 NOT NULL,
  "early_leave_minutes" integer DEFAULT 0 NOT NULL,
  "worked_minutes" integer,
  "note" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "attendance_session_clock_order_check"
    CHECK ("clock_out_at" IS NULL OR "clock_out_at" >= "clock_in_at"),
  CONSTRAINT "attendance_session_minutes_check"
    CHECK (
      "planned_break_minutes" >= 0
      AND "late_minutes" >= 0
      AND "early_leave_minutes" >= 0
      AND ("worked_minutes" IS NULL OR "worked_minutes" >= 0)
    )
);

ALTER TABLE "pos"."attendance_sessions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "pos"."attendance_events"
  ADD CONSTRAINT "attendance_events_branch_id_branches_id_fk"
    FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict,
  ADD CONSTRAINT "attendance_events_staff_id_staff_users_id_fk"
    FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE restrict,
  ADD CONSTRAINT "attendance_events_session_id_attendance_sessions_id_fk"
    FOREIGN KEY ("session_id") REFERENCES "pos"."attendance_sessions"("id") ON DELETE cascade;

ALTER TABLE "pos"."attendance_sessions"
  ADD CONSTRAINT "attendance_sessions_branch_id_branches_id_fk"
    FOREIGN KEY ("branch_id") REFERENCES "pos"."branches"("id") ON DELETE restrict,
  ADD CONSTRAINT "attendance_sessions_staff_id_staff_users_id_fk"
    FOREIGN KEY ("staff_id") REFERENCES "pos"."staff_users"("id") ON DELETE restrict,
  ADD CONSTRAINT "attendance_sessions_schedule_id_work_schedules_id_fk"
    FOREIGN KEY ("schedule_id") REFERENCES "pos"."work_schedules"("id") ON DELETE set null;

CREATE INDEX "attendance_event_branch_occurred_idx"
  ON "pos"."attendance_events" ("branch_id", "occurred_at");
CREATE INDEX "attendance_event_staff_occurred_idx"
  ON "pos"."attendance_events" ("staff_id", "occurred_at");
CREATE INDEX "attendance_event_session_idx"
  ON "pos"."attendance_events" ("session_id");
CREATE INDEX "attendance_session_branch_date_idx"
  ON "pos"."attendance_sessions" ("branch_id", "work_date");
CREATE INDEX "attendance_session_staff_clockin_idx"
  ON "pos"."attendance_sessions" ("staff_id", "clock_in_at");
CREATE INDEX "attendance_session_schedule_idx"
  ON "pos"."attendance_sessions" ("schedule_id");
CREATE UNIQUE INDEX "attendance_session_one_open_staff_idx"
  ON "pos"."attendance_sessions" ("staff_id")
  WHERE "status" = 'open';

ALTER TABLE "pos"."attendance_events"
  ADD CONSTRAINT "attendance_event_type_check"
    CHECK ("event_type" IN ('clock_in', 'clock_out')),
  ADD CONSTRAINT "attendance_event_method_check"
    CHECK ("method" IN ('qr', 'face', 'manual'));

ALTER TABLE "pos"."attendance_sessions"
  ADD CONSTRAINT "attendance_session_work_date_check"
    CHECK ("work_date" ~ '^\d{4}-(0[1-9]|1[0-2])-([012]\d|3[01])$'),
  ADD CONSTRAINT "attendance_session_clock_in_method_check"
    CHECK ("clock_in_method" IN ('qr', 'face', 'manual')),
  ADD CONSTRAINT "attendance_session_clock_out_method_check"
    CHECK ("clock_out_method" IS NULL OR "clock_out_method" IN ('qr', 'face', 'manual')),
  ADD CONSTRAINT "attendance_session_status_check"
    CHECK ("status" IN ('open', 'completed')),
  ADD CONSTRAINT "attendance_session_review_status_check"
    CHECK ("review_status" IN ('not_required', 'pending', 'approved', 'rejected')),
  ADD CONSTRAINT "attendance_session_completion_check"
    CHECK (
      ("status" = 'open' AND "clock_out_at" IS NULL AND "clock_out_method" IS NULL)
      OR
      ("status" = 'completed' AND "clock_out_at" IS NOT NULL AND "clock_out_method" IS NOT NULL)
    );

-- Attendance is available only through the authenticated application API.
-- Browser roles must never read biometric/attendance data directly.
REVOKE ALL ON TABLE
  "pos"."attendance_events",
  "pos"."attendance_sessions"
FROM public, anon, authenticated;

REVOKE ALL ON SEQUENCE
  "pos"."attendance_events_id_seq",
  "pos"."attendance_sessions_id_seq"
FROM public, anon, authenticated;

CREATE POLICY "server_only_deny_client_access"
  ON "pos"."attendance_events"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);

CREATE POLICY "server_only_deny_client_access"
  ON "pos"."attendance_sessions"
  AS RESTRICTIVE FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);
